### PR TITLE
Relative sourcemaps paths

### PR DESCRIPTION
**Pull request by n3dst4**
The sourcemaps support in 1.0 is great, but I noticed the mapped files all showed up as having absolute paths. This is a bit cumbersome to work with in browser dev tools, and leaks information about project setup etc.

This PR makes adds an option, relative-source-maps, to automatically trim process.cwd() from the start of the mapped paths (this is in line with what browserify itself does).

There's also a basedir option to override the root directory or paths.

### CODE REVIEW

**Comment by n3dst4** [comment]
Happy to tweak this to make it the default too. Might be preferable.

**Comment by andreypopp** [comment]
Thanks!

> Happy to tweak this to make it the default too. Might be preferable.

Yes, I think this is worth to be the default option. What other transforms (coffeeify, for example) do regarding this?

**Comment by n3dst4** [comment]
Not sure, but I do know that browserify itself only ever generates relative paths.

The more I think about it, the more I think it shouldn't ever be an option. Relative paths all the time?

**Comment by andreypopp** [comment]
@n3dst4 yes, I think it should be relative paths all the time.... though to be honest I think this is browserify's job to relativize them.

**Comment by n3dst4** [comment]
I know what you mean, but currently all it does is adjust the offsets :-/

Anyway, branch updated to make relative paths be always on.

**Comment by n3dst4** [comment]
Closing due to react-tools being shelved.

**Pull request closed without merging**
